<a href="https://colab.research.google.com/github/luffy6281/PortfolioProjects/blob/main/NwN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving SampleA.csv to SampleA.csv

In [ ]:
import pandas as pd
import numpy as np
import datetime

In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['SampleA.csv']))

In [ ]:
df.head()

,Post_creation_date,Page_ID,Post_ID,Post_creation_time_of_day,Video_length (s),Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
0,06-01-2021,FB003,FB003_743065,10:06:00 AM,78.016,64539,1540,60,296,30983,3828,13.77
1,06-01-2021,FB003,FB003_855641,1:12:01 PM,NaN,94086,2020,313,336,0,0,0.00
2,06-01-2021,FB003,FB003_859546,3:21:19 PM,171.051,65406,1058,54,380,30116,725,14.23
3,06-01-2021,FB003,FB003_177590,4:01:00 PM,296.128,271591,4521,425,2213,114324,8384,22.21
4,06-01-2021,FB003,FB003_173788,5:06:01 PM,NaN,44813,772,88,157,0,0,0.00

In [ ]:
df[['Post_creation_date']] = df[['Post_creation_date']].apply(pd.to_datetime)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1539 entries, 0 to 1538
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Post_creation_date         1539 non-null   datetime64[ns]
 1   Page_ID                    1539 non-null   object
 2   Post_ID                    1539 non-null   object
 3   Post_creation_time_of_day  1539 non-null   object
 4   Video_length (s)           735 non-null    float64
 5   Post_reach                 1539 non-null   int64
 6   Post_reactions             1539 non-null   int64
 7   Post_comments              1539 non-null   int64
 8   Post_shares                1539 non-null   int64
 9   Video_views                1539 non-null   int64
 10  Completed_video_views      1539 non-null   int64
 11  Avg._video_view_time (s)   1539 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(6), object(3)
memory usage: 144.4+ KB

In [ ]:
# convert "date" column to index 
#index_col ="date", makes "date" column
df = pd.read_csv("SampleA.csv", parse_dates =["Post_creation_date"], index_col ="Post_creation_date")

df.head()

,Page_ID,Post_ID,Post_creation_time_of_day,Video_length (s),Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
Post_creation_date,,,,,,,,,,,
2021-06-01,FB003,FB003_743065,10:06:00 AM,78.016,64539,1540,60,296,30983,3828,13.77
2021-06-01,FB003,FB003_855641,1:12:01 PM,NaN,94086,2020,313,336,0,0,0.00
2021-06-01,FB003,FB003_859546,3:21:19 PM,171.051,65406,1058,54,380,30116,725,14.23
2021-06-01,FB003,FB003_177590,4:01:00 PM,296.128,271591,4521,425,2213,114324,8384,22.21
2021-06-01,FB003,FB003_173788,5:06:01 PM,NaN,44813,772,88,157,0,0,0.00

In [ ]:
#Drop columns not for use here
df.drop(df.columns[[1,2,3]], axis = 1, inplace = True)
df

,Page_ID,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
Post_creation_date,,,,,,,,
2021-06-01,FB003,64539,1540,60,296,30983,3828,13.77
2021-06-01,FB003,94086,2020,313,336,0,0,0.00
2021-06-01,FB003,65406,1058,54,380,30116,725,14.23
2021-06-01,FB003,271591,4521,425,2213,114324,8384,22.21
2021-06-01,FB003,44813,772,88,157,0,0,0.00
...,...,...,...,...,...,...,...,...
2021-07-31,FB002,223811,3467,104,614,0,0,0.00
2021-07-31,FB002,265766,5747,523,2353,186010,2653,37.00
2021-07-31,FB002,205342,2841,344,425,296942,4263,24.00
2021-07-31,FB002,254846,7006,330,423,0,0,0.00
2021-07-31,FB002,344550,7331,473,3324,207997,2786,33.00

In [ ]:
# settings to display all columns
pd.set_option("display.max_columns", None)

#To display column with page FB003 only
dfA = df.loc[df.Page_ID=='FB003', :]
dfA

,Page_ID,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
Post_creation_date,,,,,,,,
2021-06-01,FB003,64539,1540,60,296,30983,3828,13.77
2021-06-01,FB003,94086,2020,313,336,0,0,0.00
2021-06-01,FB003,65406,1058,54,380,30116,725,14.23
2021-06-01,FB003,271591,4521,425,2213,114324,8384,22.21
2021-06-01,FB003,44813,772,88,157,0,0,0.00
...,...,...,...,...,...,...,...,...
2021-07-31,FB003,50614,515,81,243,183700,3509,26.00
2021-07-31,FB003,164197,2329,472,1327,216936,1554,48.00
2021-07-31,FB003,120568,1800,274,1287,122612,3263,31.00
2021-07-31,FB003,153423,1877,420,618,0,0,0.00
2021-07-31,FB003,200153,1951,585,1815,242105,2576,31.00

In [ ]:
# Resampling the data on weekly basis for Page FB003
#Calculating Mean value of all fields over a Week

dfA_M = dfA.resample('W').mean()                    ##Mean value of different fields over a week for FB003 page

dfA_M

#Engagement is the sum of likes, share and comments on a post
#Mean engagement with post in a week
dfA_M['Mean_Engagement'] = dfA_M.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Average Percent of people who engaged with the post after they saw the post (over a week)
dfA_M["Mean_Percent_engagement"] = ((dfA_M["Mean_Engagement"] / dfA_M["Post_reach"])*100)

#Mean Ratio of complete video views to the video views (over a week)
dfA_M["MeanRatio_completion"] = (dfA_M["Completed_video_views"] / dfA_M["Video_views"])
dfA_M.head(467)

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Mean_Engagement,Mean_Percent_engagement,MeanRatio_completion
Post_creation_date,,,,,,,,,,
2021-06-06,158786.565217,2877.652174,183.673913,836.717391,70639.021739,10535.695652,11.471522,3898.043478,2.454895,0.149148
2021-06-13,147117.158730,3182.634921,163.079365,831.857143,62577.825397,5741.476190,9.326667,4177.571429,2.839622,0.091749
2021-06-20,138629.322034,2334.559322,318.593220,954.067797,44356.186441,5594.559322,6.833559,3607.220339,2.602062,0.126128
2021-06-27,319564.413793,4184.155172,805.344828,2290.051724,126937.344828,12495.844828,8.944138,7279.551724,2.277961,0.098441
2021-07-04,136335.057692,2286.076923,363.557692,5507.634615,85766.365385,2852.903846,12.352115,8157.269231,5.983251,0.033264
2021-07-11,135947.877551,2250.857143,359.795918,7659.775510,90679.469388,1923.918367,19.040816,10270.428571,7.554681,0.021217
2021-07-18,136927.673469,2264.224490,376.142857,6526.346939,99998.081633,2253.571429,18.795918,9166.714286,6.694567,0.022536
2021-07-25,135646.673469,1997.551020,363.938776,9640.387755,105391.367347,1900.877551,21.346939,12001.877551,8.847897,0.018036
2021-08-01,136454.785714,2260.690476,358.047619,10730.761905,90141.500000,1990.952381,22.309524,13349.500000,9.783094,0.022087

In [ ]:
# Resampling the data on weekly basis for Page FB003
#Calculating Total value of all fields over a Week

dfA_T = dfA.resample('W').sum()          ##Total value of different fields over a week for FB003 page
dfA_T

#Engagement is the sum of likes, share and comments on a post
#Total engagement with the posts in a week 
dfA_T['Sum_Engagement'] = dfA_T.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Total Percent of people who engaged with the post after they saw the post (over a week)
dfA_T["Sum_Percent_engagement"] = ((dfA_T["Sum_Engagement"] / dfA_T["Post_reach"])*100)

#Total Ratio of complete video views to video views (over a week)
dfA_T["Sum_Ratio_completion"] = (dfA_T["Completed_video_views"] / dfA_T["Video_views"])
dfA_T

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Sum_Engagement,Sum_Percent_engagement,Sum_Ratio_completion
Post_creation_date,,,,,,,,,,
2021-06-06,7304182,132372,8449,38489,3249395,484642,527.69,179310.0,2.454895,0.149148
2021-06-13,9268381,200506,10274,52407,3942403,361713,587.58,263187.0,2.839622,0.091749
2021-06-20,8179130,137739,18797,56290,2617015,330079,403.18,212826.0,2.602062,0.126128
2021-06-27,18534736,242681,46710,132823,7362366,724759,518.76,422214.0,2.277961,0.098441
2021-07-04,7089423,118876,18905,286397,4459851,148351,642.31,424178.0,5.983251,0.033264
2021-07-11,6661446,110292,17630,375329,4443294,94272,933.00,503251.0,7.554681,0.021217
2021-07-18,6709456,110947,18431,319791,4899906,110425,921.00,449169.0,6.694567,0.022536
2021-07-25,6646687,97880,17833,472379,5164177,93143,1046.00,588092.0,8.847897,0.018036
2021-08-01,5731101,94949,15038,450692,3785943,83620,937.00,560679.0,9.783094,0.022087

In [ ]:
# settings to display all columns
pd.set_option("display.max_columns", None)

#To display column with page FB002 only
dfB = df.loc[df.Page_ID=='FB002', :]
dfB

,Page_ID,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
Post_creation_date,,,,,,,,
2021-06-01,FB002,386225,10030,344,1269,0,0,0.00
2021-06-01,FB002,58476,630,26,204,20545,916,7.28
2021-06-01,FB002,177090,2275,180,715,76999,9644,15.30
2021-06-01,FB002,187726,2925,189,523,0,0,0.00
2021-06-01,FB002,216693,3598,133,1475,77106,7286,17.18
...,...,...,...,...,...,...,...,...
2021-07-31,FB002,223811,3467,104,614,0,0,0.00
2021-07-31,FB002,265766,5747,523,2353,186010,2653,37.00
2021-07-31,FB002,205342,2841,344,425,296942,4263,24.00
2021-07-31,FB002,254846,7006,330,423,0,0,0.00
2021-07-31,FB002,344550,7331,473,3324,207997,2786,33.00

In [ ]:
# Resampling the data on weekly basis for Page FB002
#Calculating Mean value of all fields over a Week

dfB_M = dfB.resample('W').mean()                    ##Mean value of different fields over a week for FB002 page

dfB_M

#Engagement is the sum of likes, share and comments on a post
#Mean engagement with post in a week
dfB_M['Mean_Engagement'] = dfB_M.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Average Percent of people who engaged with the post after they saw the post (over a week)
dfB_M["Mean_Percent_engagement"] = ((dfB_M["Mean_Engagement"] / dfB_M["Post_reach"])*100)

#Mean Ratio of complete video views to the video views (over a week)
dfB_M["MeanRatio_completion"] = (dfB_M["Completed_video_views"] / dfB_M["Video_views"])
dfB_M

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Mean_Engagement,Mean_Percent_engagement,MeanRatio_completion
Post_creation_date,,,,,,,,,,
2021-06-06,334357.400000,5474.360000,277.860000,1322.020000,124605.960000,12757.420000,8.033000,7074.240000,2.115772,0.102382
2021-06-13,365700.881356,5570.542373,325.796610,1315.847458,150356.728814,20539.067797,9.076610,7212.186441,1.972155,0.136602
2021-06-20,212287.238806,3964.462687,424.850746,1255.313433,59008.104478,5717.656716,6.407463,5644.626866,2.658957,0.096896
2021-06-27,491636.943396,7556.264151,1192.339623,3277.962264,181877.584906,21274.113208,6.643585,12026.566038,2.446229,0.116969
2021-07-04,292841.952381,5639.333333,387.619048,1650.642857,107990.047619,5585.452381,13.409048,7677.595238,2.621754,0.051722
2021-07-11,258863.000000,5278.400000,354.800000,1427.800000,84923.971429,1606.428571,18.114286,7061.000000,2.727698,0.018916
2021-07-18,258863.000000,5278.400000,354.800000,1427.800000,90118.200000,1302.485714,13.885714,7061.000000,2.727698,0.014453
2021-07-25,258863.000000,5278.400000,354.800000,1427.800000,92450.485714,1592.457143,15.485714,7061.000000,2.727698,0.017225
2021-08-01,258863.000000,5278.400000,354.800000,1427.800000,109559.000000,1492.133333,17.933333,7061.000000,2.727698,0.013619

In [ ]:
# Resampling the data on weekly basis for Page FB002
#Calculating Total value of all fields over a Week

dfB_T = dfB.resample('W').sum()          ##Total value of different fields over a week for FB002 page
dfB_T

#Engagement is the sum of likes, share and comments on a post
#Total engagement with the posts in a week 
dfB_T['Sum_Engagement'] = dfB_T.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Total Percent of people who engaged with the post after they saw the post (over a week)
dfB_T["Sum_Percent_engagement"] = ((dfB_T["Sum_Engagement"] / dfB_T["Post_reach"])*100)

#Total Ratio of complete video views to video views (over a week)
dfB_T["Sum_Ratio_completion"] = (dfB_T["Completed_video_views"] / dfB_T["Video_views"])
dfB_T

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Sum_Engagement,Sum_Percent_engagement,Sum_Ratio_completion
Post_creation_date,,,,,,,,,,
2021-06-06,16717870,273718,13893,66101,6230298,637871,401.65,353712.0,2.115772,0.102382
2021-06-13,21576352,328662,19222,77635,8871047,1211805,535.52,425519.0,1.972155,0.136602
2021-06-20,14223245,265619,28465,84106,3953543,383083,429.30,378190.0,2.658957,0.096896
2021-06-27,26056758,400482,63194,173732,9639512,1127528,352.11,637408.0,2.446229,0.116969
2021-07-04,12299362,236852,16280,69327,4535582,234589,563.18,322459.0,2.621754,0.051722
2021-07-11,9060205,184744,12418,49973,2972339,56225,634.00,247135.0,2.727698,0.018916
2021-07-18,9060205,184744,12418,49973,3154137,45587,486.00,247135.0,2.727698,0.014453
2021-07-25,9060205,184744,12418,49973,3235767,55736,542.00,247135.0,2.727698,0.017225
2021-08-01,7765890,158352,10644,42834,3286770,44764,538.00,211830.0,2.727698,0.013619

In [ ]:
# settings to display all columns
pd.set_option("display.max_columns", None)

#To display column with page FB001 only
dfC = df.loc[df.Page_ID=='FB001', :]
dfC.head()

,Page_ID,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
Post_creation_date,,,,,,,,
2021-06-01,FB001,248638,6621,189,1013,0,0,0.00
2021-06-01,FB001,104997,4243,83,609,39641,4619,6.58
2021-06-01,FB001,83638,1666,83,434,0,0,0.00
2021-06-01,FB001,208201,6617,149,952,0,0,0.00
2021-06-01,FB001,211628,4910,226,845,0,0,0.00

In [ ]:
# Resampling the data on weekly basis for Page FB001
#Calculating Mean value of all fields over a Week

dfC_M = dfC.resample('W').mean()                    ##Mean value of different fields over a week for FB001 page

dfC_M

#Engagement is the sum of likes, share and comments on a post
#Mean engagement with post in a week
dfC_M['Mean_Engagement'] = dfC_M.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Average Percent of people who engaged with the post after they saw the post (over a week)
dfC_M["Mean_Percent_engagement"] = ((dfC_M["Mean_Engagement"] / dfC_M["Post_reach"])*100)

#Mean Ratio of complete video views to the video views (over a week)
dfC_M["MeanRatio_completion"] = (dfC_M["Completed_video_views"] / dfC_M["Video_views"])
dfC_M

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Mean_Engagement,Mean_Percent_engagement,MeanRatio_completion
Post_creation_date,,,,,,,,,,
2021-06-06,197390.244898,4260.224490,307.000000,1003.775510,20841.612245,3416.448980,3.347347,5571.000000,2.822328,0.163924
2021-06-13,203626.295082,5233.737705,251.262295,1015.508197,24594.426230,4230.622951,4.626066,6500.508197,3.192372,0.172016
2021-06-20,200744.431034,4409.862069,278.758621,1006.275862,29020.931034,3254.620690,3.624138,5694.896552,2.836889,0.112147
2021-06-27,210674.000000,4788.282609,415.956522,1136.369565,22973.000000,3762.391304,3.686304,6340.608696,3.009678,0.163774
2021-07-04,217572.023810,5268.809524,328.261905,1075.119048,37171.380952,1835.619048,8.153095,6672.190476,3.066658,0.049383
2021-07-11,239207.500000,5900.166667,357.166667,1167.500000,46079.976190,788.357143,11.428571,7424.833333,3.103930,0.017108
2021-07-18,239207.500000,5900.166667,357.166667,1167.500000,52174.761905,598.500000,11.000000,7424.833333,3.103930,0.011471
2021-07-25,239207.500000,5900.166667,357.166667,1167.500000,49184.500000,838.428571,10.428571,7424.833333,3.103930,0.017047
2021-08-01,239207.500000,5900.166667,357.166667,1167.500000,41267.444444,1057.444444,7.805556,7424.833333,3.103930,0.025624

In [ ]:
# Resampling the data on weekly basis for Page FB001
#Calculating Total value of all fields over a Week

dfC_T = dfC.resample('W').sum()          ##Total value of different fields over a week for FB001 page
dfC_T

#Engagement is the sum of likes, share and comments on a post
#Total engagement with the posts in a week 
dfC_T['Sum_Engagement'] = dfC_T.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Total Percent of people who engaged with the post after they saw the post (over a week)
dfC_T["Sum_Percent_engagement"] = ((dfC_T["Sum_Engagement"] / dfC_T["Post_reach"])*100)

#Total Ratio of complete video views to video views (over a week)
dfC_T["Sum_Ratio_completion"] = (dfC_T["Completed_video_views"] / dfC_T["Video_views"])
dfC_T

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Sum_Engagement,Sum_Percent_engagement,Sum_Ratio_completion
Post_creation_date,,,,,,,,,,
2021-06-06,9672122,208751,15043,49185,1021239,167406,164.02,272979.0,2.822328,0.163924
2021-06-13,12421204,319258,15327,61946,1500260,258068,282.19,396531.0,3.192372,0.172016
2021-06-20,11643177,255772,16168,58364,1683214,188768,210.20,330304.0,2.836889,0.112147
2021-06-27,9691004,220261,19134,52273,1056758,173070,169.57,291668.0,3.009678,0.163774
2021-07-04,9138025,221290,13787,45155,1561198,77096,342.43,280232.0,3.066658,0.049383
2021-07-11,10046715,247807,15001,49035,1935359,33111,480.00,311843.0,3.103930,0.017108
2021-07-18,10046715,247807,15001,49035,2191340,25137,462.00,311843.0,3.103930,0.011471
2021-07-25,10046715,247807,15001,49035,2065749,35214,438.00,311843.0,3.103930,0.017047
2021-08-01,8611470,212406,12858,42030,1485628,38068,281.00,267294.0,3.103930,0.025624

In [ ]:
# settings to display all columns
pd.set_option("display.max_columns", None)

#To display column with page FB004 only
dfD = df.loc[df.Page_ID=='FB004', :]
dfD

,Page_ID,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s)
Post_creation_date,,,,,,,,
2021-06-20,FB004,18080,400,6,133,5613,116,6.85
2021-06-20,FB004,10000,163,16,31,0,0,0.00
2021-06-20,FB004,16096,394,13,47,0,0,0.00
2021-06-20,FB004,6273,209,4,25,0,0,0.00
2021-06-20,FB004,21878,625,3,79,0,0,0.00
...,...,...,...,...,...,...,...,...
2021-07-31,FB004,10420,308,5,29,0,0,0.00
2021-07-31,FB004,12116,204,9,67,20723,2741,21.00
2021-07-31,FB004,19182,493,3,40,0,0,0.00
2021-07-31,FB004,41522,1052,52,200,0,0,0.00
2021-07-31,FB004,13292,402,27,46,0,0,0.00

In [ ]:
# Resampling the data on weekly basis for Page FB004
#Calculating Mean value of all fields over a Week

dfD_M = dfD.resample('W').mean()                    ##Mean value of different fields over a week for FB004 page

dfD_M

#Engagement is the sum of likes, share and comments on a post
#Mean engagement with post in a week
dfD_M['Mean_Engagement'] = dfD_M.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Average Percent of people who engaged with the post after they saw the post (over a week)
dfD_M["Mean_Percent_engagement"] = ((dfD_M["Mean_Engagement"] / dfD_M["Post_reach"])*100)

#Mean Ratio of complete video views to the video views (over a week)
dfD_M["MeanRatio_completion"] = (dfD_M["Completed_video_views"] / dfD_M["Video_views"])
dfD_M

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Mean_Engagement,Mean_Percent_engagement,MeanRatio_completion
Post_creation_date,,,,,,,,,,
2021-06-20,14465.400000,358.200000,8.400000,63.000000,1122.600000,23.200000,1.370000,429.600000,2.969845,0.020666
2021-06-27,29654.523810,610.238095,54.928571,127.595238,6831.071429,1771.880952,2.668571,792.761905,2.673325,0.259386
2021-07-04,18074.589744,441.820513,19.717949,71.974359,28253.512821,527.461538,5.734103,533.512821,2.951729,0.018669
2021-07-11,17798.666667,443.666667,18.166667,71.000000,51357.809524,809.976190,8.595238,532.833333,2.993670,0.015771
2021-07-18,17798.666667,443.666667,18.166667,71.000000,49298.904762,782.809524,11.285714,532.833333,2.993670,0.015879
2021-07-25,17798.666667,443.666667,18.166667,71.000000,66420.023810,685.642857,9.428571,532.833333,2.993670,0.010323
2021-08-01,17798.666667,443.666667,18.166667,71.000000,54411.777778,935.111111,10.444444,532.833333,2.993670,0.017186

In [ ]:
# Resampling the data on weekly basis for Page FB004
#Calculating Total value of all fields over a Week

dfD_T = dfD.resample('W').sum()          ##Total value of different fields over a week for FB004 page
dfD_T

#Engagement is the sum of likes, share and comments on a post
#Total engagement with the posts in a week 
dfD_T['Sum_Engagement'] = dfD_T.apply(lambda row: row.Post_reactions + row.Post_comments + row.Post_shares, axis = 1) 

#Total Percent of people who engaged with the post after they saw the post (over a week)
dfD_T["Sum_Percent_engagement"] = ((dfD_T["Sum_Engagement"] / dfD_T["Post_reach"])*100)

#Total Ratio of complete video views to video views (over a week)
dfD_T["Sum_Ratio_completion"] = (dfD_T["Completed_video_views"] / dfD_T["Video_views"])
dfD_T

,Post_reach,Post_reactions,Post_comments,Post_shares,Video_views,Completed_video_views,Avg._video_view_time (s),Sum_Engagement,Sum_Percent_engagement,Sum_Ratio_completion
Post_creation_date,,,,,,,,,,
2021-06-20,72327,1791,42,315,5613,116,6.85,2148.0,2.969845,0.020666
2021-06-27,1245490,25630,2307,5359,286905,74419,112.08,33296.0,2.673325,0.259386
2021-07-04,704909,17231,769,2807,1101887,20571,223.63,20807.0,2.951729,0.018669
2021-07-11,747544,18634,763,2982,2157028,34019,361.00,22379.0,2.993670,0.015771
2021-07-18,747544,18634,763,2982,2070554,32878,474.00,22379.0,2.993670,0.015879
2021-07-25,747544,18634,763,2982,2789641,28797,396.00,22379.0,2.993670,0.010323
2021-08-01,640752,15972,654,2556,1958824,33664,376.00,19182.0,2.993670,0.017186